encoding: utf-8
markdown: kramdown
pygments: false
name: "Ellen Gummesson"
description: "Random ramblings, geekiness and other musings"
permalink: "blog/:year/:month/:day/:title"
url: "http://ellengummesson.com"
author: "/humans.txt"
feed: "/feed.xml"
exclude:
  - "README.md"
  - "Gemfile"
  - "package.json"
  - "gulpfile.js"
  - "node_modules"
